title: FrameReply
description: Project, privacy, legal, and support information for FrameReply.
lang: en-US
theme: jekyll-theme-cayman
show_downloads: false
url: https://fanjin-z.github.io
baseurl: /framereply
repository: fanjin-z/framereply

relative_links:
  enabled: true
  collections: true
